theme: jekyll-theme-architect
title: Sigma Delta Technologies
description: Home page da Sigma Delta Technologies
show_downloads: false

# Google services
google_analytics: UA-97992983-2

# Jekyll plugins
plugins:
  - jekyll-redirect-from

langs:
- id: pt
  menu:
  - area: main
    label: Página principal
  - area: cv
    label: CV
  - area: articles
    label: Artigos
  - area: contact
    label: Contato
- id: en
  menu:
  - area: main
    label: Home page
  - area: cv
    label: CV
  - area: articles
    label: Articles
  - area: contact
    label: Contact
