theme: jekyll-theme-architect
title: Sigma Delta
description: Home page da Sigma Delta
show_downloads: false

# Google services
google_analytics: UA-143076561-1

# Jekyll plugins
plugins:
  - jekyll-redirect-from

langs:
  - id: pt
    menu:
    - area: main
      label: Página principal
    - area: projects
      label: Projetos
    - area: contact
      label: Contato
  - id: en
    menu:
    - area: main
      label: Home page
    - area: projects
      label: Projects
    - area: contact
      label: Contact