theme: jekyll-theme-architect
title: SIGMA DELTA TECNOLOGIA
description: Home page da Sigma Delta
show_downloads: false

# Google services
google_analytics: UA-143076561-1

# Jekyll plugins
plugins:
  - jekyll-redirect-from

langs:
  - id: pt
    menu:
    - area: main
      label: Página principal
    - area: clients
      label: Clientes
    - area: contact
      label: Contato
  - id: en
    menu:
    - area: main
      label: Home page
    - area: clients
      label: Clients
    - area: contact
      label: Contact